-- MySQL Script generated by MySQL Workbench
-- Thu Aug 12 11:42:12 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pspkarate
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pspkarate
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pspkarate` DEFAULT CHARACTER SET utf8 ;
USE `pspkarate` ;

-- -----------------------------------------------------
-- Table `pspkarate`.`club`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pspkarate`.`club` (
  `idclub` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `adresse` VARCHAR(45) NOT NULL,
  `siege_sociale` VARCHAR(45) NOT NULL,
  `licence_club` INT NOT NULL,
  PRIMARY KEY (`idclub`),
  UNIQUE INDEX `licence_club_UNIQUE` (`licence_club` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pspkarate`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pspkarate`.`role` (
  `idrole` INT NOT NULL,
  PRIMARY KEY (`idrole`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pspkarate`.`calendrier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pspkarate`.`calendrier` (
  `idcalendrier` INT NOT NULL,
  `lieu` VARCHAR(45) NULL,
  `date` DATETIME NULL,
  `theme` VARCHAR(45) NULL,
  PRIMARY KEY (`idcalendrier`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pspkarate`.`kata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pspkarate`.`kata` (
  `idkata` INT NOT NULL,
  `media 1` VARCHAR(45) NULL,
  `media2` VARCHAR(45) NULL,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idkata`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pspkarate`.`grade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pspkarate`.`grade` (
  `idgrade` INT NOT NULL,
  `couleur` VARCHAR(45) NULL,
  `acces` VARCHAR(45) NULL,
  `kata` VARCHAR(45) NULL,
  `kata_idkata` INT NOT NULL,
  PRIMARY KEY (`idgrade`),
  INDEX `fk_grade_kata1_idx` (`kata_idkata` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pspkarate`.`sportif`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pspkarate`.`sportif` (
  `idsportif` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `licence` INT NOT NULL,
  `adresse` VARCHAR(45) NULL,
  `professeur` TINYINT NULL,
  `role_idrole` INT NOT NULL,
  `calendrier_idcalendrier` INT NOT NULL,
  `club_idclub` INT NOT NULL,
  `grade_idgrade` INT NOT NULL,
  PRIMARY KEY (`idsportif`),
  UNIQUE INDEX `licence_UNIQUE` (`licence` ASC) VISIBLE,
  INDEX `fk_sportif_role_idx` (`role_idrole` ASC) VISIBLE,
  INDEX `fk_sportif_calendrier1_idx` (`calendrier_idcalendrier` ASC) VISIBLE,
  INDEX `fk_sportif_club1_idx` (`club_idclub` ASC) VISIBLE,
  INDEX `fk_sportif_grade1_idx` (`grade_idgrade` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
