-- MySQL Script generated by MySQL Workbench
-- Tue Apr 13 16:20:07 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pspkarate
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pspkarate` ;

-- -----------------------------------------------------
-- Schema pspkarate
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pspkarate` DEFAULT CHARACTER SET utf8 ;
USE `pspkarate` ;

-- -----------------------------------------------------
-- Table `pspkarate`.`calendrier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS  `pspkarate`.`calendrier` ;

CREATE TABLE IF NOT EXISTS `pspkarate`.`calendrier` (
  `idcalendrier` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `lieu` VARCHAR(45) NOT NULL,
  `theme` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcalendrier`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;



-- -----------------------------------------------------
-- Table `pspkarate`.`club`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pspkarate`.`club` ;

CREATE TABLE IF NOT EXISTS `pspkarate`.`club` (
  `idclub` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `adresse` VARCHAR(45) NOT NULL,
  `siegesocial` VARCHAR(45) NOT NULL,
  `licenceClub` INT NOT NULL,
  PRIMARY KEY (`idclub`),
  UNIQUE INDEX `licenceClub_UNIQUE` (`licenceClub` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pspkarate`.`grade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pspkarate`.`grade` ;

CREATE TABLE IF NOT EXISTS `pspkarate`.`grade` (
  `idgrade` INT NOT NULL,
  `couleur` VARCHAR(45) NOT NULL,
  `acces` BOOLEAN NOT NULL,
  `kata_nom` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idgrade`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pspkarate`.`kata`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pspkarate`.`kata` ;

CREATE TABLE IF NOT EXISTS `pspkarate`.`kata` (
  `idkata` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `media1` VARCHAR(200) NULL DEFAULT NULL,
  `media2` VARCHAR(200) NULL DEFAULT NULL,
  `grade_idgrade` INT NOT NULL,
  PRIMARY KEY (`idkata`),
  INDEX `fk_kata_grade1_idx` (`grade_idgrade` ASC) ,
  CONSTRAINT `fk_kata_grade1`
    FOREIGN KEY (`grade_idgrade`)
    REFERENCES `pspkarate`.`grade` (`idgrade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pspkarate`.`sportif`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pspkarate`.`sportif` ;

CREATE TABLE IF NOT EXISTS `pspkarate`.`sportif` (
  `idsportif` INT NOT NULL,
  `nom` VARCHAR(25) NOT NULL,
  `prenom` VARCHAR(25) NOT NULL,
  `n°licence` INT NOT NULL,
  `adresse` VARCHAR(45) NOT NULL,
  `club_idclub` INT NOT NULL,
  `grade_idgrade` INT NOT NULL,
  `professeur` BOOLEAN ,
  PRIMARY KEY (`idsportif`),
  UNIQUE INDEX `licence_UNIQUE` (`licence` ASC) ,
  INDEX `fk_sportif_club_idx` (`club_idclub` ASC) ,
  INDEX `fk_sportif_grade1_idx` (`grade_idgrade` ASC) ,
  CONSTRAINT `fk_sportif_club`
    FOREIGN KEY (`club_idclub`)
    REFERENCES `pspkarate`.`club` (`idclub`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sportif_grade1`
    FOREIGN KEY (`grade_idgrade`)
    REFERENCES `pspkarate`.`grade` (`idgrade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pspkarate`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pspkarate`.`role` ;

CREATE TABLE IF NOT EXISTS `pspkarate`.`role` (
  `idrole` INT NOT NULL,
  `sportif_idsportif` INT NOT NULL,
  PRIMARY KEY (`idrole`),
  INDEX `fk_role_sportif1_idx` (`sportif_idsportif` ASC) ,
  CONSTRAINT `fk_role_sportif1`
    FOREIGN KEY (`sportif_idsportif`)
    REFERENCES `pspkarate`.`sportif` (`idsportif`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;